kind: OperationSwitch
apiVersion: api.ibm.com/v1
metadata:
  name: OperationSwitch-ew96a
  namespace: test-pro-vcs1
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  cases:
    - conditions:
        - verbPath:
            path: /chat/completions
            verb: POST
      execute:
        - $ref: test-pro-vcs1:InvokeAzureOpenAiChatCompletions-ew96a:1.0
    - conditions:
        - verbPath:
            path: /embeddings
            verb: POST
      execute:
        - $ref: test-pro-vcs1:InvokeAzureOpenAiEmbeddings-ew96a:1.0
    - conditions:
        - verbPath:
            path: /models
            verb: GET
      execute:
        - $ref: test-pro-vcs1:InvokeAzureOpenAiModels-ew96a:1.0
    - conditions:
        - verbPath:
            path: /models/{a_model_id}
            verb: GET
      execute:
        - $ref: test-pro-vcs1:InvokeAzureOpenAiModelsId-ew96a:1.0
