kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: api-test-oai-vcs-lgu8w
  namespace: test-oai-vcs
  version: '1.0'
  tags: []
  domain: ai-platform
spec:
  api-spec:
    $path: ./api-spec-lgu8w.yml
  policy-sequence:
    - $ref: test-oai-vcs:freeflowpolicysequence-test-oai-vcs-lgu8w:1.0
