kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: product-test-oai-vcs-lgu8w
  namespace: test-oai-vcs
  version: '1.0'
  tags: []
  domain: ai-platform
  description: ''
spec:
  apis:
    - $ref: test-oai-vcs:api-test-oai-vcs-lgu8w:1.0
  plans:
    - $ref: test-oai-vcs:plan-test-oai-vcs-lgu8w:1.0
