kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: freeflowpolicysequence-test-gem-e04zz
  namespace: test-pro-vcs
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: test-pro-vcs:ExtractIdentity-e04zz:1.0
    - $ref: test-pro-vcs:Authenticate-e04zz:1.0
    - $ref: test-pro-vcs:Authorize-e04zz:1.0
    - $ref: test-pro-vcs:If-e04zz:1.0
    - $ref: test-pro-vcs:OperationSwitch-e04zz:1.0
  monitoring:
    $ref: test-pro-vcs:Telemetry-e04zz:1.0
