kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: Telemetry-e04zz
  namespace: test-pro-vcs
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  verbosity:
    - level: basic
      onSuccessTrimTo: normal
      inboundLevel: basic
      outboundLevel: basic
      operations:
        - path: /models/{a_model_id}:batchEmbedContents
          method: POST
        - path: /models/{a_model_id}:countTokens
          method: POST
        - path: /models/{a_model_id}:embedContent
          method: POST
        - path: /models/{a_model_id}:generateContent
          method: POST
        - path: /models
          method: GET
        - path: /models/{a_model_id}
          method: GET
