kind: If
apiVersion: api.ibm.com/v1
metadata:
  name: If-lgu8w
  namespace: test-oai-vcs
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  condition: ($pathParameter('a_model_id'))
  execute:
    - $ref: test-oai-vcs:Set-lgu8w:1.0
