kind: Plan
apiVersion: api.ibm.com/v1
metadata:
  name: plan-test-gem-e04zz
  namespace: test-pro-vcs
  version: '1.0'
  tags: []
  description: ''
  domain: ai-platform
spec:
  qos:
    withQuota:
      gemini-token-weighted:
        - $ref: test-pro-vcs:gemini-token-weighted-e04zz:1.0
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: test-pro-vcs:api-test-gem-e04zz:1.0
            operations:
              - path: /models/{a_model_id}:batchEmbedContents
                method: post
              - path: /models/{a_model_id}:countTokens
                method: post
              - path: /models/{a_model_id}:embedContent
                method: post
              - path: /models/{a_model_id}:generateContent
                method: post
              - path: /models
                method: get
              - path: /models/{a_model_id}
                method: get
        telemetry: {}
    dp-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: test-pro-vcs:api-test-gem-e04zz:1.0
            operations:
              - path: /models/{a_model_id}:batchEmbedContents
                method: post
              - path: /models/{a_model_id}:countTokens
                method: post
              - path: /models/{a_model_id}:embedContent
                method: post
              - path: /models/{a_model_id}:generateContent
                method: post
              - path: /models
                method: get
              - path: /models/{a_model_id}
                method: get
