kind: LLMProvider
apiVersion: api.ibm.com/v1
metadata:
  name: test-gem
  namespace: test-pro-vcs
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
  domain: ai-platform
spec:
  provider:
    type: gemini
    operations:
      - InvokeGeminiModels
      - InvokeGeminiModelsId
      - InvokeGeminiGenerateContent
      - InvokeGeminiEmbedContent
      - InvokeGeminiBatchEmbedContents
      - InvokeGeminiCountTokens
    apiKeySecret: testgem
    tlsClientProfile: tls-client-profile-default:1.0.0
    region: us-south
    opVersion: '2024-03-14'
    cachePolicy:
      cache:
        expire:
          static:
            seconds: 60
        scope:
          narrowScope: {}
        ignoreControlDirectives: true
  product:
    $ref: test-pro-vcs:product-test-gem-e04zz:1.0
